server:
  port: 6666
spring:
  application:
    name: yc.batch
  batch:
    job:
      enabled: false
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update # 自动创建|更新|验证数据库表结构 none表示不更新
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: public
        temp:
          use_jdbc_metadata_defaults: false
    show-sql: true
    open-in-view: true
  jackson:
    property-naming-strategy: SNAKE_CASE
    serialization:
      fail-on-empty-beans: false


logging:
  level:
    org:
      springframework: WARN
      hibernate: WARN

datasource-reader:
#  type: com.alibaba.druid.pool.DruidDataSource
  url: jdbc:postgresql://localhost:5432/postgres
  username: postgres
  password: postgres
#  driver-class-name: com.mysql.jdbc.Driver
  continue-on-error: false
  sql-script-encoding: UTF-8